version: "3.7"

services:
  zybots-docx:
    networks:
      - backend
    image: senthilsweb/zybots-docx
    container_name: zybots-docx
    restart: unless-stopped
    tty: true
    ports:
      - "4444:3000"
    volumes:
      - ./data:/src/data
networks:
  backend: